name: Tests

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{github.workspace}}/coverage/lcov.info

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: pnpm install

      - name: Prepare typecheck
        run: echo '{"token":"token"}' > config.json
      - name: Run typecheck
        run: pnpm run typecheck

  build:
    runs-on: ubuntu-latest
    needs:
      - typecheck
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm run build